<meta http-equiv="Content-Language" content="en-gb">
<%

output = "<p class=""head1"">FACTS AND FIGURES</p>"
output = output & "<p>Links to a comprehensive collection of facts and figures for " & datediff("yyyy","1886-09-01",now) & " years of matches, players and officials.</p>"
output = output & "<p><b>Version:</b> 1.0</p>"
output = output & "<p><b>Date:</b> 30 Jun 2011</p>"

output = output & "<p class=""noprint"" style=""margin:0 0 6 0;""><a href=""argylehistorymenu.asp"">Return to History Contents</a></p>"

output = output & "</div>"

output = output & "<br><table border=""1""  cellpadding=""0"" cellspacing=""0"" style=""border-collapse:collapse;"" width=""744"">"
  output = output & "<tr>"
    output = output & "<td nowrap rowspan=""16"" valign=""top""><b><p style=""margin: 6 0 3 0; font-size: 12px"">1886-1903</p></b></td>"
    output = output & "<td colspan=""10""><b><font color=""#457b44""><p style=""margin: 6 0 3 0; font-size: 12px"">ARGYLE FOOTBALL CLUB</p></b></td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1886-87</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8687F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8687S"">Sec XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8687P"">Players</a></td>"
    output = output & " <td nowrap><b>1894-95</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9495F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9495P"">Players</a></td>"
    output = output & "<td colspan=""3"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1887-88</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8788F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8788S"">Sec XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8788P"">Players</a></td>"
    output = output & "<td colspan=""6"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1888-89</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8889F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8889S"">Sec XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8889P"">Players</a></td>"
    output = output & " <td nowrap><b>1897-98</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9798F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9798R"">Res XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9798P"">Players</a></td>"
    output = output & "<td colspan=""2"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1889-90</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8990F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8990S"">Sec XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=8990P"">Players</a></td>"
    output = output & " <td nowrap><b>1898-99</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9899F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9899R"">Res XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9899P"">Players</a></td>"
    output = output & "<td colspan=""2"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1890-91</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9091F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9091S"">Sec XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9091P"">Players</a></td>"
    output = output & " <td nowrap><b>1899-00</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9900F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9900R"">Res XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9900P"">Players</a></td>"
    output = output & "<td colspan=""2"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & "<td nowrap><b>1891-92</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9192F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9192P"">Players</a></td>"
    output = output & " <td nowrap>&nbsp;</td>"
    output = output & " <td nowrap><b>1900-01</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0001F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0001R"">Res XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0001WF"">Wed XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0001WA"">Wed A XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0001P"">Players</a></td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1892-93</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9293F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9293P"">Players</a></td>"
    output = output & " <td nowrap>&nbsp;</td>"
    output = output & " <td nowrap><b>1901-02</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0102F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0102R"">Res XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0102WF"">Wed XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0102P"">Players</a></td>"
    output = output & " <td nowrap>&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1893-94</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9394F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=9394P"">Players</a></td>"
    output = output & " <td nowrap>&nbsp;</td>"
    output = output & " <td nowrap><b>1902-03</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0203F"">First XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0203WF"">Wed XI</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=0203P"">Players</a></td>"
    output = output & "<td colspan=""2"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>PLAYERS</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersA-B"">A - B</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersC-D"">C - D</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersE-G"">E - G</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersH-J"">H - J</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersK-M"">K - M</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersN-R"">N - R</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersS"">S</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=playersT-Z"">T - Z</a></td>"
    output = output & " <td nowrap>&nbsp;</td>"
  output = output & "</tr>"
  output = output & "</tr>"
    output = output & "<tr>"
    output = output & " <td><b>OTHER INFO</b></td>"
    output = output & " <td><a href=""argylehistory_amateurstats.asp?stat=notedpeopleA-M"">Noted People A-M</a></td>"
    output = output & " <td><a href=""argylehistory_amateurstats.asp?stat=notedpeopleN-Z"">Noted People N-Z</a></td>"
    output = output & " <td><a href=""argylehistory_amateurstats.asp?stat=footballofficials"">Football Officials</a></td>"
    output = output & " <td><a href=""argylehistory_amateurstats.asp?stat=AACofficials"">Ath. Club Officials</a></td>"
    output = output & " <td><a href=""argylehistory_amateurstats.asp?stat=competitions"">Comp'tions</a></td>"
    output = output & " <td><a href=""argylehistory_amateurstats.asp?stat=clubrecords"">Club Records</a></td>"
    output = output & " <td><a href=""argylehistory_amateurstats.asp?stat=playerrecords"">Player Records</a></td>"
    output = output & "<td colspan=""2"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & "<td colspan=""10""><b><font color=""#457b44""><p style=""margin: 9 0 3 0; font-size: 12px"">ARGYLE RUGBY FOOTBALL CLUB</p></b></td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1900-01</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0001F"">First XV</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0001R"">Res XV</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0001P"">Players</a></td>"
    output = output & "<td colspan=""6"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1901-02</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0102F"">First XV</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0102R"">Res XV</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0102P"">Players</a></td>"
    output = output & "<td colspan=""6"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>1902-03</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0203F"">First XV</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0203WF"">Wed XV</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=R0203P"">Players</a></td>"
    output = output & "<td colspan=""6"">&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & " <td nowrap><b>PLAYERS</b></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersA-B"">A - B</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersC-D"">C - D</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersE-G"">E - G</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersH-J"">H - J</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersK-M"">K - M</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersN-R"">N - R</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersS"">S</a></td>"
    output = output & " <td nowrap><a href=""argylehistory_amateurstats.asp?stat=RplayersT-Z"">T - Z</a></td>"
    output = output & " <td nowrap>&nbsp;</td>"
  output = output & "</tr>"
  output = output & "<tr>"
    output = output & "<td nowrap rowspan=""2"" valign=""top""><b><p style=""margin: 9 0 3 0; font-size: 12px"">1903-Now</p></b></td>"
    output = output & "<td colspan=""10""><b><font color=""#457b44""><p style=""margin: 9 0 3 0; font-size: 12px"">PLYMOUTH ARGYLE FOOTBALL CLUB</p></b></td>"
  output = output & "</tr>"
  output = output & "<tr>"    
    output = output & " <td nowrap><a href=""gosdb.asp"">GoS-DB</a></td>"
    output = output & "<td colspan=""9"">&nbsp;</td>"
  output = output & "</tr>"

 output = output & "</table>"
 
 'formheading = "<p style=""margin: 0 0 6 0;"">Feel free to leave your thoughts about this annex by completing the boxes below. If you have a general comment to make about the history project as a whole, please use the feedback facility on the <a href=""argylehistorymenu.asp""><u>contents page</u></a>.</p>"
 %>
 <!--#include file="argylehistory_form.asp"-->
 <%
  
%>